// av1_entropy.v - AV1 entropy coder core
//
// This module now matches the reference range-coder behavior for the
// existing RTL bool/literal interface instead of the old debug bit-packer.
// It keeps emitted bytes in an internal buffer until finalize so carry
// propagation can still update previously generated bytes before they are
// exposed on the RTL byte stream.
//
// Current interface coverage:
//   - init:         reset encoder state for a new frame
//   - encode_bool:  arithmetic-code one boolean using prob_q15
//   - encode_lit:   arithmetic-code a literal as equiprobable bits
//   - finalize:     flush buffered bytes and stream them out
//
// Reference: libaom / SVT-AV1 od_ec_enc style range coder

module av1_entropy #(
    parameter integer BUF_BYTES = 262144
) (
    input  wire        clk,
    input  wire        rst_n,

    // Control
    input  wire        init,
    input  wire        encode_bool,
    input  wire        encode_lit,
    input  wire        encode_symbol,
    input  wire        finalize,

    input  wire        bool_val,
    input  wire [14:0] bool_prob,
    input  wire [7:0]  lit_val,
    input  wire [4:0]  lit_bits,
    input  wire [4:0]  symbol,
    input  wire [4:0]  nsyms,
    input  wire [255:0] icdf_flat,

    output reg         busy,
    output reg         done,

    // Output byte stream
    output reg         byte_valid,
    output reg  [7:0]  byte_out,
    output reg  [23:0] bytes_written
);

    localparam [2:0] S_IDLE   = 3'd0;
    localparam [2:0] S_LIT    = 3'd1;
    localparam [2:0] S_FINISH = 3'd2;
    localparam [2:0] S_OUT    = 3'd3;

    reg [2:0]  state;

    // Range coder state
    reg [15:0] rng_reg;
    reg [63:0] low_reg;
    integer    cnt_reg;

    // Buffered output bytes. Bytes are released only after finalize so carry
    // propagation can still modify earlier bytes safely.
    reg [7:0] out_buf [0:BUF_BYTES-1];
    integer   out_len;
    integer   out_rd_idx;
    reg       overflow_seen;

    // Literal state
    reg [7:0]  lit_data_reg;
    reg [4:0]  lit_pos_reg;

    // Final flush state
    reg [63:0] fin_e_reg;
    reg [63:0] fin_n_reg;
    integer    fin_c_reg;
    integer    fin_s_reg;

    function integer ilog_nz;
        input [15:0] val;
        integer tmp;
        begin
            ilog_nz = 0;
            tmp = val;
            while (tmp > 0) begin
                ilog_nz = ilog_nz + 1;
                tmp = tmp >> 1;
            end
            if (ilog_nz < 1)
                ilog_nz = 1;
        end
    endfunction

    function [63:0] mask_bits;
        input integer bits;
        begin
            if (bits <= 0)
                mask_bits = 64'd0;
            else if (bits >= 64)
                mask_bits = {64{1'b1}};
            else
                mask_bits = (64'd1 << bits) - 64'd1;
        end
    endfunction

    function [15:0] icdf_entry;
        input [255:0] flat;
        input integer idx;
        begin
            icdf_entry = (flat >> (idx * 16)) & 256'hFFFF;
        end
    endfunction

    task bump_prior_bytes;
        input integer start_pos;
        integer idx;
        reg carry;
        reg [8:0] sum;
        begin
            carry = 1'b1;
            for (idx = start_pos - 1; idx >= 0 && carry; idx = idx - 1) begin
                sum = {1'b0, out_buf[idx]} + 9'd1;
                out_buf[idx] = sum[7:0];
                carry = sum[8];
            end
        end
    endtask

    task append_bytes_be;
        input [63:0] value;
        input integer num_bytes;
        integer idx;
        begin
            for (idx = num_bytes - 1; idx >= 0; idx = idx - 1) begin
                if (out_len < BUF_BYTES) begin
                    out_buf[out_len] = (value >> (idx * 8)) & 64'hFF;
                    out_len = out_len + 1;
                end else begin
                    overflow_seen = 1'b1;
                end
            end
        end
    endtask

    task normalize_range;
        input  [63:0] low_in;
        input  [15:0] rng_in;
        input  integer cnt_in;
        output [63:0] low_out;
        output [15:0] rng_out;
        output integer cnt_out;
        integer d;
        integer c;
        integer s;
        integer num_bytes;
        integer start_pos;
        reg [63:0] low_tmp;
        reg [63:0] out_word;
        reg [63:0] carry_mask;
        reg carry;
        begin
            low_tmp = low_in;
            d = 16 - ilog_nz(rng_in);
            c = cnt_in;
            s = c + d;

            if (s >= 40) begin
                num_bytes = (s >> 3) + 1;
                c = c + 24 - (num_bytes << 3);
                out_word = low_tmp >> c;
                low_tmp = low_tmp & mask_bits(c);
                carry_mask = 64'd1 << (num_bytes * 8);
                carry = (out_word & carry_mask) != 0;
                out_word = out_word & (carry_mask - 64'd1);
                start_pos = out_len;
                append_bytes_be(out_word, num_bytes);
                if (carry && start_pos > 0)
                    bump_prior_bytes(start_pos);
                s = c + d - 24;
            end

            low_out = low_tmp << d;
            rng_out = rng_in << d;
            cnt_out = s;
        end
    endtask

    task encode_bool_once;
        input in_val;
        input [14:0] prob_q15;
        integer split;
        reg [63:0] low_tmp;
        reg [15:0] rng_tmp;
        integer cnt_tmp;
        begin
            low_tmp = low_reg;
            rng_tmp = rng_reg;
            split = ((((rng_tmp >> 8) * (prob_q15 >> 6)) >> 1) + 4);

            if (in_val)
                low_tmp = low_tmp + rng_tmp - split;
            if (in_val)
                rng_tmp = split[15:0];
            else
                rng_tmp = rng_tmp - split[15:0];

            normalize_range(low_tmp, rng_tmp, cnt_reg, low_tmp, rng_tmp, cnt_tmp);
            low_reg = low_tmp;
            rng_reg = rng_tmp;
            cnt_reg = cnt_tmp;
        end
    endtask

    task encode_symbol_once;
        input [4:0] symbol_in;
        input [4:0] nsyms_in;
        input [255:0] icdf_in;
        integer split_lo;
        integer split_hi;
        integer nsym_last;
        reg [15:0] fl;
        reg [15:0] fh;
        reg [63:0] low_tmp;
        reg [15:0] rng_tmp;
        integer cnt_tmp;
        begin
            low_tmp = low_reg;
            rng_tmp = rng_reg;
            nsym_last = nsyms_in - 1;
            fl = (symbol_in > 0) ? icdf_entry(icdf_in, symbol_in - 1) : 16'd32768;
            fh = icdf_entry(icdf_in, symbol_in);

            if (fl < 16'd32768) begin
                split_lo = ((((rng_tmp >> 8) * (fl >> 6)) >> 1) + 4 * (nsym_last - (symbol_in - 1)));
                split_hi = ((((rng_tmp >> 8) * (fh >> 6)) >> 1) + 4 * (nsym_last - symbol_in));
                low_tmp = low_tmp + rng_tmp - split_lo;
                rng_tmp = split_lo - split_hi;
            end else begin
                split_hi = ((((rng_tmp >> 8) * (fh >> 6)) >> 1) + 4 * (nsym_last - symbol_in));
                rng_tmp = rng_tmp - split_hi;
            end

            normalize_range(low_tmp, rng_tmp, cnt_reg, low_tmp, rng_tmp, cnt_tmp);
            low_reg = low_tmp;
            rng_reg = rng_tmp;
            cnt_reg = cnt_tmp;
        end
    endtask

    integer finish_shift;
    reg [8:0] finish_val;
    integer finish_start_pos;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            busy          = 1'b0;
            done          = 1'b0;
            byte_valid    = 1'b0;
            byte_out      = 8'd0;
            bytes_written = 24'd0;
            state         = S_IDLE;
            rng_reg       = 16'h8000;
            low_reg       = 64'd0;
            cnt_reg       = -9;
            out_len       = 0;
            out_rd_idx    = 0;
            overflow_seen = 1'b0;
            lit_data_reg  = 8'd0;
            lit_pos_reg   = 5'd0;
            fin_e_reg     = 64'd0;
            fin_n_reg     = 64'd0;
            fin_c_reg     = 0;
            fin_s_reg     = 0;
        end else begin
            done       = 1'b0;
            byte_valid = 1'b0;

            case (state)
                S_IDLE: begin
                    busy = 1'b0;

                    if (init) begin
                        rng_reg       = 16'h8000;
                        low_reg       = 64'd0;
                        cnt_reg       = -9;
                        out_len       = 0;
                        out_rd_idx    = 0;
                        overflow_seen = 1'b0;
                        bytes_written = 24'd0;
                        done          = 1'b1;
                    end else if (encode_bool) begin
                        encode_bool_once(bool_val, bool_prob);
                        done = 1'b1;
                    end else if (encode_symbol) begin
                        encode_symbol_once(symbol, nsyms, icdf_flat);
                        done = 1'b1;
                    end else if (encode_lit) begin
                        lit_data_reg = lit_val;
                        lit_pos_reg  = lit_bits;
                        busy         = 1'b1;
                        state        = S_LIT;
                    end else if (finalize) begin
                        fin_e_reg = ((low_reg + 64'h3FFF) & ~64'h3FFF) | 64'h4000;
                        fin_c_reg = cnt_reg;
                        fin_s_reg = cnt_reg + 10;
                        fin_n_reg = mask_bits(cnt_reg + 16);
                        busy      = 1'b1;
                        state     = S_FINISH;
                    end
                end

                S_LIT: begin
                    busy = 1'b1;
                    if (lit_pos_reg > 0) begin
                        encode_bool_once(lit_data_reg[lit_pos_reg - 1'b1], 15'd16384);
                        lit_pos_reg = lit_pos_reg - 1'b1;
                    end else begin
                        busy  = 1'b0;
                        done  = 1'b1;
                        state = S_IDLE;
                    end
                end

                S_FINISH: begin
                    busy = 1'b1;
                    if (fin_s_reg > 0) begin
                        finish_shift = fin_c_reg + 16;
                        finish_val = fin_e_reg >> finish_shift;
                        finish_start_pos = out_len;
                        if (out_len < BUF_BYTES) begin
                            out_buf[out_len] = finish_val[7:0];
                            out_len = out_len + 1;
                        end else begin
                            overflow_seen = 1'b1;
                        end
                        if (finish_val[8] && finish_start_pos > 0)
                            bump_prior_bytes(finish_start_pos);
                        fin_e_reg = fin_e_reg & fin_n_reg;
                        fin_s_reg = fin_s_reg - 8;
                        fin_c_reg = fin_c_reg - 8;
                        fin_n_reg = fin_n_reg >> 8;
                    end else begin
                        out_rd_idx    = 0;
                        bytes_written = 24'd0;
                        state         = S_OUT;
                    end
                end

                S_OUT: begin
                    busy = 1'b1;
                    if (out_rd_idx < out_len) begin
                        byte_valid    = 1'b1;
                        byte_out      = out_buf[out_rd_idx];
                        out_rd_idx    = out_rd_idx + 1;
                        bytes_written = bytes_written + 1'b1;
                    end else begin
                        busy  = 1'b0;
                        done  = 1'b1;
                        state = S_IDLE;
                    end
                end

                default: begin
                    busy  = 1'b0;
                    state = S_IDLE;
                end
            endcase
        end
    end

endmodule
