// Generated by scripts/gen_av1_tx4x4_chroma_tables.py from AOM token_cdfs.h

function [255:0] eob_multi16_chroma_icdf_flat_qctx;
    input [1:0] qctx;
    begin
        case (qctx)
            2'd0: begin
                eob_multi16_chroma_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd18205,16'd23080,16'd27818,16'd29521};
            end
            2'd1: begin
                eob_multi16_chroma_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd13660,16'd18509,16'd23270,16'd25131};
            end
            2'd2: begin
                eob_multi16_chroma_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd9202,16'd14527,16'd19498,16'd21629};
            end
            2'd3: begin
                eob_multi16_chroma_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd3059,16'd6724,16'd11002,16'd13193};
            end
            default: eob_multi16_chroma_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd3059,16'd6724,16'd11002,16'd13193};
        endcase
    end
endfunction

function [255:0] eob_extra_chroma4_icdf_flat_qctx;
    input [1:0] qctx;
    input [5:0] ctx;
    begin
        case (qctx)
            2'd0: begin
                case (ctx)
                    6'd0: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd13699};
                    6'd1: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd10243};
                    6'd2: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd19391};
                    6'd3: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd4: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd5: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd6: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd7: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd8: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    default: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                endcase
            end
            2'd1: begin
                case (ctx)
                    6'd0: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd12433};
                    6'd1: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11101};
                    6'd2: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd17950};
                    6'd3: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd4: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd5: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd6: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd7: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd8: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    default: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                endcase
            end
            2'd2: begin
                case (ctx)
                    6'd0: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd12678};
                    6'd1: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd13324};
                    6'd2: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd15482};
                    6'd3: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd4: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd5: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd6: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd7: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd8: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    default: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                endcase
            end
            2'd3: begin
                case (ctx)
                    6'd0: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11352};
                    6'd1: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11913};
                    6'd2: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd9358};
                    6'd3: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd4: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd5: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd6: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd7: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    6'd8: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                    default: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
                endcase
            end
            default: eob_extra_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16384};
        endcase
    end
endfunction

function [255:0] coeff_base_eob_chroma4_icdf_flat_qctx;
    input [1:0] qctx;
    input [5:0] ctx;
    begin
        case (qctx)
            2'd0: begin
                case (ctx)
                    6'd0: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2742,16'd11403};
                    6'd1: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd345,16'd2256};
                    6'd2: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd147,16'd1110};
                    6'd3: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd887,16'd3138};
                    default: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd887,16'd3138};
                endcase
            end
            2'd1: begin
                case (ctx)
                    6'd0: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1556,16'd6174};
                    6'd1: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd186,16'd1560};
                    6'd2: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd131,16'd933};
                    6'd3: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd562,16'd2173};
                    default: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd562,16'd2173};
                endcase
            end
            2'd2: begin
                case (ctx)
                    6'd0: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1673,16'd5510};
                    6'd1: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd145,16'd964};
                    6'd2: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd240,16'd1005};
                    6'd3: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd262,16'd1330};
                    default: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd262,16'd1330};
                endcase
            end
            2'd3: begin
                case (ctx)
                    6'd0: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1184,16'd4891};
                    6'd1: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd40,16'd598};
                    6'd2: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd80,16'd613};
                    6'd3: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd66,16'd549};
                    default: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd66,16'd549};
                endcase
            end
            default: coeff_base_eob_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd66,16'd549};
        endcase
    end
endfunction

function [255:0] coeff_base_chroma4_icdf_flat_qctx;
    input [1:0] qctx;
    input [5:0] ctx;
    begin
        case (qctx)
            2'd0: begin
                case (ctx)
                    6'd0: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11007,16'd16324,16'd26466};
                    6'd1: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd293,16'd1230,16'd9728};
                    6'd2: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1272,16'd4316,16'd17572};
                    6'd3: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4254,16'd9822,16'd22748};
                    6'd4: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd9267,16'd15906,16'd26235};
                    6'd5: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd17692,16'd22952,16'd29230};
                    6'd6: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd243,16'd893,16'd8324};
                    6'd7: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1133,16'd3844,16'd16887};
                    6'd8: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4302,16'd9895,16'd22846};
                    6'd9: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd9077,16'd15802,16'd26241};
                    6'd10: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd15548,16'd21465,16'd28654};
                    6'd11: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd12: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd13: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd14: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd15: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd16: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd17: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd18: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd19: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd20: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd21: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd559,16'd1998,16'd12567};
                    6'd22: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1510,16'd4697,16'd18014};
                    6'd23: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd6251,16'd12582,16'd24390};
                    6'd24: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd10790,16'd17469,16'd26852};
                    6'd25: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd14867,16'd21185,16'd28500};
                    6'd26: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd187,16'd743,16'd8407};
                    6'd27: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd825,16'd2663,16'd14095};
                    6'd28: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd5192,16'd10524,16'd22572};
                    6'd29: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd12351,16'd18419,16'd27273};
                    6'd30: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd21270,16'd25353,16'd30092};
                    6'd31: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd183,16'd810,16'd8090};
                    6'd32: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd937,16'd2862,16'd14139};
                    6'd33: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd6453,16'd12044,16'd23404};
                    6'd34: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd14674,16'd20450,16'd28127};
                    6'd35: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd21189,16'd25381,16'd30010};
                    6'd36: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd299,16'd926,16'd7335};
                    6'd37: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1357,16'd3479,16'd13973};
                    6'd38: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd9176,16'd15184,16'd25124};
                    6'd39: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd17721,16'd23754,16'd29360};
                    6'd40: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd41: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    default: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                endcase
            end
            2'd1: begin
                case (ctx)
                    6'd0: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8400,16'd13765,16'd24313};
                    6'd1: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd164,16'd747,16'd9205};
                    6'd2: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd833,16'd3322,16'd16531};
                    6'd3: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd3410,16'd8769,16'd22044};
                    6'd4: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8352,16'd15240,16'd26043};
                    6'd5: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd15943,16'd21841,16'd28841};
                    6'd6: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd134,16'd480,16'd6455};
                    6'd7: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd673,16'd2673,16'd15338};
                    6'd8: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd3089,16'd8162,16'd21652};
                    6'd9: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd7499,16'd14384,16'd25573};
                    6'd10: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd13453,16'd19916,16'd28042};
                    6'd11: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd12: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd13: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd14: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd15: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd16: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd17: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd18: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd19: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd20: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd21: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd285,16'd1120,16'd9946};
                    6'd22: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd839,16'd3135,16'd16044};
                    6'd23: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4043,16'd9735,16'd22507};
                    6'd24: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8240,16'd14928,16'd25739};
                    6'd25: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11266,16'd18882,16'd27901};
                    6'd26: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd277,16'd876,16'd7470};
                    6'd27: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1256,16'd3438,16'd14959};
                    6'd28: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd6189,16'd11439,16'd23100};
                    6'd29: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd13792,16'd19812,16'd27994};
                    6'd30: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd21228,16'd25738,16'd30446};
                    6'd31: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd225,16'd848,16'd7296};
                    6'd32: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1136,16'd3381,16'd14811};
                    6'd33: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd6368,16'd12175,16'd23572};
                    6'd34: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd13566,16'd20063,16'd28088};
                    6'd35: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd19332,16'd24312,16'd29851};
                    6'd36: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd194,16'd709,16'd6297};
                    6'd37: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd859,16'd2985,16'd14310};
                    6'd38: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd6812,16'd13304,16'd24368};
                    6'd39: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd15562,16'd21795,16'd28956};
                    6'd40: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd41: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    default: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                endcase
            end
            2'd2: begin
                case (ctx)
                    6'd0: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd5872,16'd10712,16'd21960};
                    6'd1: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd92,16'd455,16'd7029};
                    6'd2: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd547,16'd2565,16'd15480};
                    6'd3: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2872,16'd7890,16'd21409};
                    6'd4: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd7875,16'd15001,16'd25819};
                    6'd5: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd14697,16'd20972,16'd28481};
                    6'd6: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd63,16'd247,16'd4888};
                    6'd7: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd354,16'd1764,16'd13730};
                    6'd8: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2000,16'd6423,16'd20204};
                    6'd9: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd5989,16'd12821,16'd24499};
                    6'd10: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11094,16'd18111,16'd27094};
                    6'd11: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd12: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd13: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd14: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd15: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd16: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd17: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd18: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd19: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd20: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd21: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd97,16'd449,16'd7026};
                    6'd22: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd314,16'd1604,16'd13211};
                    6'd23: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2013,16'd6387,16'd19387};
                    6'd24: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd6046,16'd11302,16'd22667};
                    6'd25: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd5943,16'd13118,16'd23559};
                    6'd26: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd336,16'd851,16'd5661};
                    6'd27: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1565,16'd3875,16'd14712};
                    6'd28: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd6004,16'd11334,16'd22568};
                    6'd29: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd13266,16'd19855,16'd28108};
                    6'd30: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd20264,16'd25838,16'd30400};
                    6'd31: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd155,16'd610,16'd5808};
                    6'd32: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd737,16'd2763,16'd14140};
                    6'd33: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4536,16'd10326,16'd22535};
                    6'd34: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11252,16'd18138,16'd27297};
                    6'd35: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd15659,16'd22001,16'd29533};
                    6'd36: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd76,16'd328,16'd5072};
                    6'd37: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd330,16'd1601,16'd12736};
                    6'd38: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4326,16'd11427,16'd24068};
                    6'd39: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd10973,16'd17937,16'd27106};
                    6'd40: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd41: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    default: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                endcase
            end
            2'd3: begin
                case (ctx)
                    6'd0: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4928,16'd10666,16'd23448};
                    6'd1: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd44,16'd304,16'd5711};
                    6'd2: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd459,16'd2500,16'd16437};
                    6'd3: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd3048,16'd8833,16'd22449};
                    6'd4: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8662,16'd16320,16'd26579};
                    6'd5: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd13960,16'd21884,16'd29179};
                    6'd6: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd20,16'd144,16'd3742};
                    6'd7: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd181,16'd1261,16'd13542};
                    6'd8: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1565,16'd5847,16'd20076};
                    6'd9: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd5133,16'd13236,16'd25719};
                    6'd10: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd9516,16'd17099,16'd25041};
                    6'd11: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd12: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd13: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd14: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd15: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd16: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd17: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd18: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd19: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd20: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd21: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd20,16'd143,16'd4712};
                    6'd22: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd99,16'd693,16'd10385};
                    6'd23: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1019,16'd5670,16'd17351};
                    6'd24: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd5578,16'd6275,16'd14641};
                    6'd25: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd10923,16'd16384,16'd27307};
                    6'd26: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd184,16'd677,16'd4786};
                    6'd27: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd796,16'd2900,16'd13723};
                    6'd28: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4836,16'd10502,16'd22371};
                    6'd29: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11268,16'd19071,16'd26778};
                    6'd30: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd17664,16'd25856,16'd30976};
                    6'd31: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd50,16'd267,16'd4570};
                    6'd32: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd199,16'd1247,16'd11234};
                    6'd33: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2751,16'd7551,16'd21659};
                    6'd34: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd6617,16'd17644,16'd27097};
                    6'd35: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd14043,16'd18725,16'd28087};
                    6'd36: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd27,16'd188,16'd4080};
                    6'd37: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd107,16'd689,16'd10192};
                    6'd38: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4428,16'd10627,16'd22141};
                    6'd39: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4681,16'd18725,16'd23406};
                    6'd40: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    6'd41: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                    default: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
                endcase
            end
            default: coeff_base_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8192,16'd16384,16'd24576};
        endcase
    end
endfunction

function [255:0] coeff_br_chroma4_icdf_flat_qctx;
    input [1:0] qctx;
    input [5:0] ctx;
    begin
        case (qctx)
            2'd0: begin
                case (ctx)
                    6'd0: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd6482,16'd9863,16'd16801};
                    6'd1: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8189,16'd12114,16'd19234};
                    6'd2: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd12233,16'd16676,16'd23264};
                    6'd3: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd15865,16'd20200,16'd25793};
                    6'd4: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd18748,16'd22677,16'd27404};
                    6'd5: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd20911,16'd24398,16'd28411};
                    6'd6: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd25550,16'd27834,16'd30262};
                    6'd7: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1832,16'd3953,16'd9736};
                    6'd8: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd3049,16'd6064,16'd13228};
                    6'd9: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd5671,16'd9799,16'd17610};
                    6'd10: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd9118,16'd13903,16'd21360};
                    6'd11: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd12518,16'd17320,16'd23883};
                    6'd12: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd15352,16'd19915,16'd25660};
                    6'd13: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd21288,16'd24727,16'd28537};
                    6'd14: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd3612,16'd6278,16'd12945};
                    6'd15: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd3836,16'd6839,16'd13878};
                    6'd16: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd5335,16'd9277,16'd17108};
                    6'd17: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8280,16'd12992,16'd20621};
                    6'd18: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11119,16'd15994,16'd23040};
                    6'd19: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd13702,16'd18491,16'd24849};
                    6'd20: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd18583,16'd22598,16'd27328};
                    default: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd18583,16'd22598,16'd27328};
                endcase
            end
            2'd1: begin
                case (ctx)
                    6'd0: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd7019,16'd10536,16'd17197};
                    6'd1: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd7394,16'd11193,16'd18262};
                    6'd2: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11199,16'd15679,16'd22579};
                    6'd3: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd14853,16'd19467,16'd25452};
                    6'd4: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd17578,16'd21856,16'd26985};
                    6'd5: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd19680,16'd23613,16'd28008};
                    6'd6: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd23994,16'd26802,16'd29775};
                    6'd7: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1990,16'd3865,16'd9344};
                    6'd8: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2478,16'd5102,16'd11993};
                    6'd9: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4469,16'd8358,16'd16294};
                    6'd10: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd7781,16'd12588,16'd20297};
                    6'd11: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11329,16'd16281,16'd23358};
                    6'd12: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd14239,16'd19154,16'd25232};
                    6'd13: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd19219,16'd23182,16'd27720};
                    6'd14: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd3012,16'd5478,16'd11678};
                    6'd15: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2742,16'd5366,16'd11972};
                    6'd16: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd3799,16'd7283,16'd14949};
                    6'd17: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd6306,16'd10859,16'd18908};
                    6'd18: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd9239,16'd14274,16'd21766};
                    6'd19: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11871,16'd16839,16'd23815};
                    6'd20: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16314,16'd20850,16'd26320};
                    default: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16314,16'd20850,16'd26320};
                endcase
            end
            2'd2: begin
                case (ctx)
                    6'd0: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4873,16'd8267,16'd15374};
                    6'd1: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd5583,16'd9348,16'd16879};
                    6'd2: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8898,16'd13635,16'd21207};
                    6'd3: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd12924,16'd17956,16'd24483};
                    6'd4: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16218,16'd20725,16'd26272};
                    6'd5: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd19091,16'd23194,16'd27997};
                    6'd6: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd22624,16'd25938,16'd29165};
                    6'd7: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2568,16'd5064,16'd11112};
                    6'd8: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2257,16'd4853,16'd11444};
                    6'd9: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd3771,16'd7432,16'd15441};
                    6'd10: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd6735,16'd11387,16'd19351};
                    6'd11: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd10430,16'd15343,16'd22636};
                    6'd12: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd13135,16'd17752,16'd24188};
                    6'd13: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16357,16'd21291,16'd27074};
                    6'd14: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1318,16'd2988,16'd8652};
                    6'd15: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1177,16'd3073,16'd8915};
                    6'd16: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2340,16'd5154,16'd12683};
                    6'd17: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4193,16'd8433,16'd17442};
                    6'd18: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd7958,16'd13296,16'd20954};
                    6'd19: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8001,16'd14157,16'd22547};
                    6'd20: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd12447,16'd18210,16'd25079};
                    default: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd12447,16'd18210,16'd25079};
                endcase
            end
            2'd3: begin
                case (ctx)
                    6'd0: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2380,16'd4816,16'd11343};
                    6'd1: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd3734,16'd6930,16'd14706};
                    6'd2: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd7960,16'd12887,16'd20812};
                    6'd3: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11788,16'd17768,16'd25050};
                    6'd4: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd16625,16'd21514,16'd27066};
                    6'd5: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd15904,16'd23680,16'd27870};
                    6'd6: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd20861,16'd25992,16'd29089};
                    6'd7: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1105,16'd2608,16'd9474};
                    6'd8: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd932,16'd2872,16'd8371};
                    6'd9: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2175,16'd5640,16'd13523};
                    6'd10: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd6364,16'd12943,16'd19566};
                    6'd11: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd8811,16'd13471,16'd21190};
                    6'd12: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd11398,16'd19471,16'd24695};
                    6'd13: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd13023,16'd21845,16'd27307};
                    6'd14: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd834,16'd2247,16'd5401};
                    6'd15: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd828,16'd2097,16'd7864};
                    6'd16: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd1469,16'd4308,16'd9693};
                    6'd17: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd2351,16'd9110,16'd18368};
                    6'd18: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4443,16'd8886,16'd18883};
                    6'd19: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd4915,16'd9830,16'd18022};
                    6'd20: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd5461,16'd16384,16'd27307};
                    default: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd5461,16'd16384,16'd27307};
                endcase
            end
            default: coeff_br_chroma4_icdf_flat_qctx = {16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd0,16'd5461,16'd16384,16'd27307};
        endcase
    end
endfunction
